### ISSUE TITLE
Error: CSRF token missing

### ISSUE THREAD

**Issue by d-staehler** [d-staehler/Bookstore#8]
When returning from paypal

**Comment by d-staehler** [comment]
`Error: CSRF token missing
   at checkCsrf (/Users/DJ/Desktop/Books/Bookstore/node_modules/lusca/lib/csrf.js:89:18)
   at checkCsrf (eval at createToggleWrapper (/Users/DJ/Desktop/Books/Bookstore/node_modules/meddleware/index.js:133:51), <anonymous>:1:70)
   at Layer.handle [as handle_request] (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:312:13)
   at /Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:280:7
   at param (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:349:14)
   at param (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:410:3)
   at next (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:271:10)
   at xframe (/Users/DJ/Desktop/Books/Bookstore/node_modules/lusca/lib/xframes.js:12:9)
   at /Users/DJ/Desktop/Books/Bookstore/node_modules/lusca/index.js:48:21
   at lusca (/Users/DJ/Desktop/Books/Bookstore/node_modules/lusca/index.js:53:9)
   at lusca (eval at createToggleWrapper (/Users/DJ/Desktop/Books/Bookstore/node_modules/meddleware/index.js:133:51), <anonymous>:1:66)
   at Layer.handle [as handle_request] (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:312:13)
   at /Users/DJ/Desktop/Books/Bookstore/node_modules/express/lib/router/index.js:280:7`
